name: Deploy Ubixen IDE to GitHub Pages (Private)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Embed API Key for Private Deployment
      run: |
        # Create a copy of IDE.html for deployment
        cp IDE.html index.html
        
        # Replace localStorage-based API key with embedded secret
        sed -i "s|this\.judgeApiKey = localStorage\.getItem('judge0-api-key') || null;|this.judgeApiKey = '${{ secrets.JUDGE0_API_KEY }}';|" index.html
        
        # Also replace the RapidAPI headers to use the embedded key
        sed -i "s|'X-RapidAPI-Key': this\.judgeApiKey|'X-RapidAPI-Key': '${{ secrets.JUDGE0_API_KEY }}'|g" index.html
        
        # Update API key validation logic for embedded keys
        sed -i "s|this\.validateApiKey();|// this.validateApiKey(); // API key embedded - validation disabled|" index.html
        
        # Verify the replacement worked
        if grep -q '${{ secrets.JUDGE0_API_KEY }}' index.html; then
          echo "✅ API key embedded successfully!"
          echo "API key found in these locations:"
          grep -n '${{ secrets.JUDGE0_API_KEY }}' index.html | head -3
        else
          echo "❌ API key embedding failed!"
          echo "Looking for line containing localStorage:"
          grep -n "localStorage\.getItem('judge0-api-key')" index.html || echo "Line not found"
          exit 1
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
